import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from './_components/Sidebar'
 
 
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function UserLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className="flex flex-row bg-black" >
                {/* Sidebar */}
                <Sidebar/>
        {/* Body */}
      <main className='flex flex-1 p'>
      {children}
      </main>
        <div className='xl:w-[500px]'></div>
        </body>
    </html>
  )
}
